#!/bin/bash

# music-rename
# ######################
# renames music files & folders to be terminal friendly.
#
# * whitespaces become -
# * uppercase becomes lowercase
# * any other characters besides alphanumeric characters or dashes are deleted

for FILE in $(cat $1)
do
	new="$1"

	# replace all whitespace with -
	new=$(echo $new | tr " " -)

	# if file has more than two dashes, flatten dashes into one
	if [[ $new =~ '/\s{2,}' ]]; then
		new=$(echo $new | 

	# check for more than one dash instance, flatten to one
	new=$(echo $new | tr "--" -)

	# letters become lowercase


	# rename file/folder
	mv $1 $new
done
