#!/bin/bash

yt-dlp \
	-f 'bv[height>=1080][ext=mp4]+ba[ext=m4a]' \
	--merge-output-format mp4 \
	--yes-playlist \
	--write-subs \
	--write-auto-subs \
	--sub-format 'best' \
	--embed-subs \
	--embed-thumbnail \
	--embed-metadata \
	$1 \
	-o '%(channel)s/%(playlist_title)s/%(upload_date)s-%(title)s.%(ext)s' \
	--download-archive 'dl.txt'
